### ISSUE TITLE
Hogg error?

### ISSUE THREAD

**Issue by martinceresa** [CIFASIS/QuickFuzz#10]
``` bash
tools/hogg.hs:910:32:
    Couldn't match expected type ‘time-1.5.0.1:Data.Time.Format.Locale.TimeLocale’
                with actual type ‘System.Locale.TimeLocale’
    NB: ‘time-1.5.0.1:Data.Time.Format.Locale.TimeLocale’
          is defined in ‘Data.Time.Format.Locale’ in package ‘time-1.5.0.1’
        ‘System.Locale.TimeLocale’
          is defined in ‘System.Locale’ in package ‘old-locale-1.0.0.7’
    In the first argument of ‘formatTime’, namely ‘defaultTimeLocale’
    In the expression: formatTime defaultTimeLocale "%B %Y" currentTime
Failed to install hogg-0.4.1.2
cabal: Error: some packages failed to install:
hogg-0.4.1.2 failed during the building phase. The exception was:
ExitFailure 1
```

Configs:

-- This is the configuration file for the 'cabal' command line tool.

-- The available configuration options are listed below.
-- Some of them have default values listed.

-- Lines (like this one) beginning with '--' are comments.
-- Be careful with spaces and indentation because they are
-- used to indicate layout for nested sections.

remote-repo: hackage.haskell.org:http://hackage.haskell.org/packages/archive
remote-repo-cache: /home/martin/.cabal/packages
-- local-repo:
-- logs-dir:
world-file: /home/martin/.cabal/world
-- verbose: 1
compiler: ghc
with-compiler: ghc-7.10.2.20150906
with-hc-pkg: ghc-pkg-7.10.2.20150906
-- scratchdir:
-- program-prefix: 
-- program-suffix: 
-- library-vanilla: True
-- library-profiling: False
-- shared: False
-- executable-dynamic: False
-- executable-profiling: False
optimization: True
-- library-for-ghci: True
-- split-objs: False
-- executable-stripping: True
-- user-install: True
-- package-db:
-- flags:
-- extra-include-dirs:
-- extra-lib-dirs:
-- tests: False
-- library-coverage: False
-- benchmarks: False
-- cabal-lib-version:
-- constraint:
-- preference:
-- solver: choose
-- documentation: False
-- doc-index-file: $datadir/doc/index.html
-- max-backjumps: 200
-- reorder-goals: False
-- shadow-installed-packages:
-- reinstall: False
-- avoid-reinstalls: False
-- force-reinstalls: False
-- upgrade-dependencies: False
-- only-dependencies: False
-- root-cmd:
-- symlink-bindir:
build-summary: /home/martin/.cabal/logs/build.log
-- build-log:
remote-build-reporting: anonymous
-- one-shot: False
-- jobs:
-- username:
-- password:

install-dirs user
  -- prefix: /home/martin/.cabal
  -- bindir: $prefix/bin
  -- libdir: $prefix/lib
  -- libsubdir: $pkgid/$compiler
  -- libexecdir: $prefix/libexec
  -- datadir: $prefix/share
  -- datasubdir: $pkgid
  -- docdir: $datadir/doc/$pkgid
  -- htmldir: $docdir/html
  -- haddockdir: $htmldir

install-dirs global
  -- prefix: /usr/local
  -- bindir: $prefix/bin
  -- libdir: $prefix/lib
  -- libsubdir: $pkgid/$compiler
  -- libexecdir: $prefix/libexec
  -- datadir: $prefix/share
  -- datasubdir: $pkgid
  -- docdir: $datadir/doc/$pkgid
  -- htmldir: $docdir/html
  -- haddockdir: $htmldir

**Comment by pablobuiras** [comment]
HOgg doesn't work on GHC 7.10 because of a major change in the time-1.5.0.1 package, i.e. it doesn't require old-locale any more and provides its own locale type instead. Code using old-locale such as HOgg needs to be ported.

**Comment by gaa-cifasis** [comment]
I think we fixed that in our [hogg fork](https://github.com/CIFASIS/hogg/).

**Comment by gaa-cifasis** [comment]
It was a configuration issue.
