### ISSUE TITLE
Hongfuzz integration

### ISSUE THREAD

**Issue by gaa-cifasis** [CIFASIS/QuickFuzz#15]

**Comment by tpltnt** [comment]
[honggfuzz repo](https://github.com/google/honggfuzz) (to safe the time for searching)

**Comment by gaa-cifasis** [comment]
Thanks!, we already have a fork of [honggfuzz](https://github.com/CIFASIS/honggfuzz) and the support for it in QuickFuzz is already commited. Soon i will close this issue.

**Comment by gaa-cifasis** [comment]
Done.
