### ISSUE TITLE
Error building 

### ISSUE THREAD

**Issue by varnerac** [CIFASIS/QuickFuzz#33]
I get the following building on OS X with latest `stack` from Homebrew:

```
   stack install
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/varnerac/QuickFuzz/.stack-work/logs/language-lua-0.9.0.log

    Configuring language-lua-0.9.0...
    setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: The program 'alex' is required but it
    could not be found.
```

```
stack --version
Version 1.1.2 x86_64 hpack-0.14.0
uname -a
15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
```

It's worth nothing that I set all of the flags in the `stack.yaml` file to `true`

```
flags:
  QuickFuzz:
    imgs : true
    archs : true
    docs : true
    codes : true
    media : true
    pki : true
```

**Comment by varnerac** [comment]
Changing `codes` to `false` resolve the problem. Leaving this issue open as this is most likely a bug.

**Comment by gaa-cifasis** [comment]
Hi,

I think this is a known issue in stack. To compile with 'codes', you need to have alex in your PATH. So you should execute in the QuickFuzz directory:

```
$ stack install alex
```

Then, you can compile this tool with 'codes' flag.

**Comment by varnerac** [comment]
Thanks.

**Comment by gaa-cifasis** [comment]
Btw, is QuickFuzz working correctly in OSX? We are very interested to test it there, but unfortunately MacBooks are extremely expensive to buy here... :(

**Comment by varnerac** [comment]
So, I am working on some contributions. `zzuf` works , but there is an issue with `honggfuzz`. I am about to submit a PR to put this project under CI. I'd like to have tests and build instructions to look at in GH and CircleCI, so I am gonna see if I can but the infrastructure in place.

**Comment by gaa-cifasis** [comment]
Oh, great!. Thanks for all the contributions! Btw, honggfuzz is not functional right now (something about filenames)...
