### ISSUE TITLE
Support standard in and out

### ISSUE THREAD

**Issue by varnerac** [CIFASIS/QuickFuzz#38]
QuickFuzz generates a file of the fuzzed data. For actions, including fuzzing engines, that support reading from standard in and writing to standard out, we should allow QuickFuzz to generate the dataset for the grammar in memory, pipe it to the fuzzing engine, receive the mutated binary from the fuzzing engine's standard out and the pipe it to the system under test. We can avoid unnecessary disc reads and writes.

**Comment by gaa-cifasis** [comment]
The support for using stdin input (only) to fuzz data with zzuf and radamsa is done (357d6d1). Next step is to add the option to pipe data to the tested program.

**Comment by gaa-cifasis** [comment]
Our new intern, @agustinmista is working on this right now. He will add stdin support to test programs.

**Comment by gaa-cifasis** [comment]
Done.

**Comment by varnerac** [comment]
I'd like to reopen this or open a new one. I wanted to add the ability to send data to standard in. I did not intend to remove the ability to pass a file path to the system under test.

I think we should feed the system under test via from standard in when there is no "@@" in the command args. Some programs we want to test do not take data from standard in. If the command args include "@@", we should write the file normally.

**Comment by gaa-cifasis** [comment]
It sends data using stdin if there is no @@. Otherwise, it should be work as usual. Btw, i know there are some bugs in the minimization process if the process uses stdin input but i should fix them soon.

**Comment by varnerac** [comment]
Ah, and so it does. I'll create new issues for the stuff I am finding.
