### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by varnerac** [CIFASIS/QuickFuzz#54]
It looks like https://github.com/CIFASIS/QuickFuzz/commit/80dcd33f36057ead22cb3f9cbffe3e60a57b0e72 broke master.

You can see the results in CircleCI here: https://circleci.com/gh/NineFX/QuickFuzz/74

**Comment by gaa-cifasis** [comment]
I just fixed this issue, but the last build failed. This last error is just an out-of-memory error that you get from time to time. As soon as i get a good build, i will close this issue.

**Comment by varnerac** [comment]
I will look at the out of memory errors. I don't have a great solution now. However, in the interim, retrying the build will usually clear the status indicator in GitHub.
