### ISSUE TITLE
how can I use it

### ISSUE THREAD

**Issue by DogeWatch** [CIFASIS/QuickFuzz#63]
After execute install.sh, I don't know how to use it, there is no command called QuickFuzz, and I also can't find any executable files.

**Comment by gaa-cifasis** [comment]
El 28-02-2017 23:37, DogeWatch escribió:
> After execute install.sh, I don't know how to use it, there is no
> command called QuickFuzz, and I also can't find any executable files.

Hi!

If you want to test our tool fast, you have an example crashing giffix 
here:

http://quickfuzz.org/

To avoid compiling the Haskell code, just use the pre-compiled version 
available in our website.

Let me know if you need anything!

**Comment by DogeWatch** [comment]
Thanks a lot. I have downloaded the QuickFuzz.bzexe, and use command "bzexe -d QuickFuzz.bzexe", but it told me "bzexe: QuickFuzz.bzexe probably not in gzexe format, file unchanged."
And there is another question, when I run install.sh, it ask me for a github username and password

**Comment by gaa-cifasis** [comment]
El 01-03-2017 00:07, DogeWatch escribió:
> Thanks a lot. I have downloaded the QuickFuzz.bzexe, and use command
> "bzexe -d QuickFuzz.bzexe", but it told me "bzexe: QuickFuzz.bzexe
> probably not in gzexe format, file unchanged."

You should be able to run QuickFuzz.bzexe directly (use chmod +x if it 
does not have executable permissions).

> And there is another question, when I run install.sh, it ask me for a
> github username and password

I'm not sure why, the install.sh script is old and no longer in use (in 
fact, I need to delete it!). If you want to compile your own binary, 
just follow this guide:

https://github.com/CIFASIS/QuickFuzz#installation

Please contact me at gg@cifasis-conicet.gov.ar if you need more specific 
instructions.

**Comment by DogeWatch** [comment]
Oh, I see. Thank you.
