### ISSUE TITLE
TemplateHaskell build error

### ISSUE THREAD

**Issue by dkasak** [CIFASIS/QuickFuzz#65]
While trying to build QuickFuzz with the `codes` flag

    stack build --flag QuickFuzz:codes

I get the following error(s)

    QuickFuzz-0.1.0.0: configure
    QuickFuzz-0.1.0.0: build

    If the above build failed with a linker error or .so/DLL error, addressing these may help:
    Warning: modules not listed in QuickFuzz.cabal for 'QuickFuzz' component (add to other-modules):
        Args
        ByteString
        Check
        CommandExec
        Exceptions
        Mutation
        Parallel
        Process
        Unicode

    --  While building package QuickFuzz-0.1.0.0 using:
        /home/dkasak/.local/share/stack/setup-exe-cache/x86_64-linux-tinfo6/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-1.22.5.0 build exe:QuickFuzz --ghc-options " -ddump-hi -ddump-to-file"
        Process exited with code: ExitFailure 1
        Logs have been written to: /home/dkasak/code/projects/QuickFuzz/.stack-work/logs/QuickFuzz-0.1.0.0.log

        QuickFuzz-0.1.0.0: configure
        singleBuild: invariant violated, missing package ID missing
        EXCEPTION: browse:
                readCreateProcess: stack "build" "--only-configure" "." (exit 1): failed
        
        /home/dkasak/code/projects/QuickFuzz/src/Css.hs:48:3:
            Function binding for ‘performAttr’ has no equations
            When splicing a TH declaration:

I suppose the bit regarding unlisted modules is just noise in this case (though it should probably be fixed). The relevant part seems to be the TH splice resulting in a function binding with no equations. There's also a stack error, but I surmise this is just due to the TH error. Any tips?

**Comment by gaa-cifasis** [comment]
Uhm. Let me re-compile it, to try to reproduce this issue.

**Comment by dkasak** [comment]
Any luck reproducing this?

**Comment by gaa-cifasis** [comment]
I think I know where is the problem. Nevertheless, we will release a refactoring of QuickFuzz very soon, so this issue won't be a problem, I think.

**Comment by dkasak** [comment]
Okay, thanks, I guess it isn't worthwhile to keep poking at this for now, then. Do you have a rough ETA for the new release?

**Comment by gaa-cifasis** [comment]
We are squashing some bugs, and we will try to release it this week. If you want to test it first, let me [know](mailto:gg@cifasis-conicet.gov.ar).

**Comment by gaa-cifasis** [comment]
This should be solved now.
