### ISSUE TITLE
The documentation for shrinking is out of date

### ISSUE THREAD

**Issue by gelisam** [CIFASIS/QuickFuzz#71]
The [documentation](https://github.com/CIFASIS/QuickFuzz#example) gives the example

    $ QuickFuzz test gif "./gif2webp @@ -o /dev/null" -l 1 -s 3692945303624111961 -f radamsa -r

but "test" is not (no longer?) a valid command. There is a "reduce" command, but I haven't figure out how to use it.

**Comment by gelisam** [comment]
Taking a [closer look](https://github.com/CIFASIS/QuickFuzz/blob/2e48f62454533f344b3f96c17c404698fa7c0c21/app/Run/Shrink.hs#L12) at the implementation of "reduce", it doesn't look like the feature is implemented yet?

**Comment by gaa-cifasis** [comment]
Uhm, in fact it says: 

`$ QuickFuzz gentest gif "./gif2webp @@ -o /dev/null" -l 1 -s 3692945303624111961 -f radamsa -r`

Is this not working? 

Btw, the implementation of the shrink/reduce command is integrated into gentest and muttest. I should remove the "reduce" command.

**Comment by gelisam** [comment]
> Uhm, in fact it says:
> 
>     $ QuickFuzz gentest gif "./gif2webp @@ -o /dev/null" -l 1 -s 3692945303624111961 -f radamsa -r

Oops! I copied the text from the [website](http://quickfuzz.org/), but linked to the github version of that text without realizing that they were subtly different. It is the website version which is incorrect, my apologies for linking to the wrong place.

> Is this not working?

Not quite! The documentation claims that this reduces the crashing input, but it looks like it is reducing a different input. For example:

    $ QuickFuzz gentest regex "false" -q 10 -f radamsa
    Test case number 1 has failed.
    Moving to outdir/QuickFuzz.72765061945.1.8915287786907852875.1.regex
    Test case number 2 has failed.
    Moving to outdir/QuickFuzz.72765061945.2.8049140095087974565.2.regex
    Test case number 3 has failed.
    Moving to outdir/QuickFuzz.72765061945.3.3554621185070159163.3.regex
    Test case number 4 has failed.
    Moving to outdir/QuickFuzz.72765061945.4.2172736542367791280.4.regex
    Test case number 5 has failed.
    Moving to outdir/QuickFuzz.72765061945.5.8566886643514755218.5.regex
    Test case number 6 has failed.
    Moving to outdir/QuickFuzz.72765061945.6.257316543738319118.6.regex
    Test case number 7 has failed.
    Moving to outdir/QuickFuzz.72765061945.7.6417970174950615178.7.regex
    Test case number 8 has failed.
    Moving to outdir/QuickFuzz.72765061945.8.5117423502530234193.8.regex
    Test case number 9 has failed.
    Moving to outdir/QuickFuzz.72765061945.9.2851115349742885079.9.regex
    Test case number 10 has failed.
    Moving to outdir/QuickFuzz.72765061945.10.3689708695183381774.10.regex
    10 random files tested.
    Finished!
    $ QuickFuzz gentest regex "false" -s 2851115349742885079 -f radamsa -r
    Test case number 1 has failed.
    Moving to outdir/QuickFuzz.72817851142.1.2851115349742885079.1.regex
    Shrinking over bytes has begun...
    Testing shrink of size 27
    Testing shrink of size 26
    Testing shrink of size 25
    Testing shrink of size 24
    Testing shrink of size 23
    Testing shrink of size 22
    Testing shrink of size 21
    Testing shrink of size 20
    Testing shrink of size 19
    Testing shrink of size 18
    Testing shrink of size 17
    Testing shrink of size 16
    Testing shrink of size 15
    Testing shrink of size 14
    Testing shrink of size 13
    Testing shrink of size 12
    Testing shrink of size 11
    Testing shrink of size 10
    Testing shrink of size 9
    Testing shrink of size 8
    Testing shrink of size 7
    Testing shrink of size 6
    Testing shrink of size 5
    Testing shrink of size 4
    Testing shrink of size 3
    Testing shrink of size 2
    Testing shrink of size 1
    Testing shrink of size 0
    Shrinking finished
    Reduced from 27 bytes to 0 bytes
    After executing 28 shrinks with 28 failing shrinks.
    Saving to outdir/QuickFuzz.72817851142.1.2851115349742885079.1.regex.reduced
    1 random files tested.
    Finished!

Looks good so far, but...

    $ wc -c outdir/*.2851115349742885079.*.regex
    15 outdir/QuickFuzz.72765061945.9.2851115349742885079.9.regex
    27 outdir/QuickFuzz.72817851142.1.2851115349742885079.1.regex
    42 total

The file I wanted to shrink had 15 characters, but QuickFuzz generated and reduced a different file from 27 characters down to 0.

> Btw, the implementation of the shrink/reduce command is integrated into gentest and muttest. I should remove the "reduce" command.

Is that a good idea? If I recall correctly, at the Compose Conference 2016 presentation about QuickFuzz, the presenter explained that once an input was discovered to be bad, it should be kept as-is and reduced again once the bug has been fixed, because those bad inputs sometimes trigger more than one bug, whereas the shrunk input usually only triggers one. From the command-line options of `QuickFuzz reduce`, it looks like the command would re-run and reduce all the inputs from a particular folder, which seems like a much more useful way of extracting new bugs from existing known-bad inputs than running `QuickFuzz gentest ... -s <seed> -r` one seed at a time.

**Comment by gaa-cifasis** [comment]
> Oops! I copied the text from the website, but linked to the github version of that text without realizing that they were subtly different. It is the website version which is incorrect, my apologies for linking to the wrong place.

My bad. I should update the website ASAP.

Let me review your test case. It could be a bug. @agustinmista can you take a quick look to it?

> Is that a good idea? If I recall correctly, at the Compose Conference 2016 presentation about QuickFuzz, the presenter explained that once an input was discovered to be bad, it should be kept as-is and reduced again once the bug has been fixed, because those bad inputs sometimes trigger more than one bug, whereas the shrunk input usually only triggers one. From the command-line options of QuickFuzz reduce, it looks like the command would re-run and reduce all the inputs from a particular folder, which seems like a much more useful way of extracting new bugs from existing known-bad inputs than running QuickFuzz gentest ... -s <seed> -r one seed at a time.

I'm one of the presenter of QuickFuzz in Compose ~~2016~~ 2017. Hello fellow composer! 😃 
I'm happy to know someone was interested enough to test our tool and we love the feedback: we can still implement reduce as you said. Indeed it can be useful, but it will only work reducing bytes (one by one, like here), and we plan to use the shrink feature from QuickCheck to reduce all kind of types. Then, if you want to reduce a value from an arbitrary type, then you need to have it first: so we re-generate it.

**Comment by gelisam** [comment]
> I'm one of the presenter of QuickFuzz in Compose ~2016~ 2017. Hello fellow composer! 😃

Hello! 😃

> I'm happy to know someone was interested enough to test our tool

Let me tell you more about how we're using it then! We have an application written in Haskell which uses a custom input format, and we would like to fuzz its input in order to detect some bugs we might have missed. Since our application is written in Haskell, we already have a datatype describing our input format, so it should be easy to add a custom format to my local copy of QuickFuzz by deriving an Arbitrary instance for that datatype.

I have written a small test application with an intentional bug, and I am happy to say that with this approach, QuickFuzz managed to find both the intentional bug and an unintentional bug! This makes me quite confident that QuickFuzz will be helpful for testing the larger application we care about.

> we plan to use the shrink feature from QuickCheck to reduce all kind of types. Then, if you want to reduce a value from an arbitrary type, then you need to have it first: so we re-generate it.

Interesting, so instead of shrinking the fuzzed input which caused the failure, you shrink the intermediate, pre-fuzzed input and hope that re-applying the external fuzzer with the same seed will reproduce the part of the modification which caused the failure?

**Comment by gaa-cifasis** [comment]
> Let me tell you more about how we're using it then! We have an application written in Haskell which uses a custom input format, and we would like to fuzz its input in order to detect some bugs we might have missed. Since our application is written in Haskell, we already have a datatype describing our input format, so it should be easy to add a custom format to my local copy of QuickFuzz by deriving an Arbitrary instance for that datatype.
>
> I have written a small test application with an intentional bug, and I am happy to say that with this approach, QuickFuzz managed to find both the intentional bug and an unintentional bug! This makes me quite confident that QuickFuzz will be helpful for testing the larger application we care about.

Neat! In fact, AFAIK you only need the arbitrary instances of your. Then QuickCheck could take care of the rest. In that case, you can test without executing (and therefore, forking) and should be a lot faster.

> Interesting, so instead of shrinking the fuzzed input which caused the failure, you shrink the intermediate, pre-fuzzed input and hope that re-applying the external fuzzer with the same seed will reproduce the part of the modification which caused the failure?

That's correct. We are already identifying which bits are modified by the fuzzer and trying to [re-apply such mutations](https://github.com/CIFASIS/QuickFuzz/blob/b010f90dc310b3e8e0b0f760219614c43e21bfc3/app/Utils/Shrink.hs#L44). That was part of the excelent work made by our intern, @agustinmista 

Nevertheless, I think the most interesting idea regarding shriking is to reduce the original type, not the bytestring of the encode value. We are still working in a general approach to define shrink.

**Comment by agustinmista** [comment]
Hello everyone!

First of all, thank you @gelisam for your feedback! 

As @gaa-cifasis said, if you already have the definition  of the data type you want to generate, you could probably only need the automatic generator derivation machinery from QuickFuzz and not the testing frontend, letting QuickCheck to do the testing stuff without all the execution overhead. In this version of QuickFuzz, the automatic derivation tools are split into a separated library inside the same package, so you could probably use it as a dependency on your project without needing to compile the frontend.

Recalling your example, it took me a while to realize what was happening. Unfortunately, the generation doesn't depend only on the seed, but also on the generation size (controlled by the *-l/--lower* and *-u/--upper* bounding flags). This way you can have a little more control over the generated values. If you see a generated test case filename, the number after the seed is the generation size. So, you can regenerate the value using both the seed and the size parameters. For example:

```
$ QuickFuzz gentest regex "false" -q 5  -l 50 -u 54  -f radamsa
Test case number 1 has failed. 
Moving to outdir/QuickFuzz.12068995218.1.3125067542585630486.50.regex
Test case number 2 has failed. 
Moving to outdir/QuickFuzz.12068995218.2.6381620074804546666.51.regex
Test case number 3 has failed. 
Moving to outdir/QuickFuzz.12068995218.3.1129984083802977037.52.regex
Test case number 4 has failed. 
Moving to outdir/QuickFuzz.12068995218.4.380706884796019556.53.regex
Test case number 5 has failed. 
Moving to outdir/QuickFuzz.12068995218.5.1688157967501929243.54.regex
5 random files tested.
Finished!

```
Then, to regenerate a test case (the fifth one in this case), you must provide both the seed and the generation size:

```
$ QuickFuzz gentest regex "false" -r -s 1688157967501929243 -f radamsa -l 54 -u 54
Test case number 1 has failed. 
Moving to outdir/QuickFuzz.12264722613.1.1688157967501929243.54.regex
Shrinking over bytes has begun...
Testing shrink of size 72
Testing shrink of size 71
Testing shrink of size 70
...
Testing shrink of size 1
Testing shrink of size 0
Shrinking finished
Reduced from 72 bytes to 0 bytes
After executing 73 shrinks with 73 failing shrinks. 
Saving to outdir/QuickFuzz.12264722613.1.1688157967501929243.54.regex.reduced
1 random files tested.
Finished!
```
Finally, if we compare the original file and the regenerated one we can see that now it works as expected:

```
$ wc -c outdir/*.1688157967501929243.54.*
 72 outdir/QuickFuzz.12068995218.5.1688157967501929243.54.regex
 72 outdir/QuickFuzz.12264722613.1.1688157967501929243.54.regex
  0 outdir/QuickFuzz.12264722613.1.1688157967501929243.54.regex.reduced
144 total

$ diff -s outdir/QuickFuzz.12068995218.5.1688157967501929243.54.regex outdir/QuickFuzz.12264722613.1.1688157967501929243.54.regex
Files outdir/QuickFuzz.12068995218.5.1688157967501929243.54.regex and outdir/QuickFuzz.12264722613.1.1688157967501929243.54.regex are identical
```
I hope you find this explanation helpful! 

PS: I think this kind of information should be more visible for newcomers to QuickFuzz. @gaa-cifasis maybe we could open a little wiki gathering more usage examples and documentation in the future.

**Comment by gaa-cifasis** [comment]
@gelisam

Can you confirm that the use of seed **and size** produces the expected result?

**Comment by gelisam** [comment]
I confirm, thanks!

**Comment by gaa-cifasis** [comment]
Great. Thanks!
