### ISSUE TITLE
Website unavailable 

### ISSUE THREAD

**Issue by ZhuoZoeyChen** [CIFASIS/QuickFuzz#77]
Hello~

The website [QuickFuzz.org](http://quickfuzz.org) is down.

Is it possible for you guys to share the documentations here?

Thanks a lot!

**Comment by chreekat** [comment]
And now the domain has been poached. :(

**Comment by martinceresa** [comment]
Hi guys! Sorry for the troubles, [`here it is the new web`](http://quickfuzz.cifasis-conicet.gov.ar/).
